server:
  port: 8888

spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#  config: classpath:config/logback-spring.xml


mybatis:
  mapper-locations: classpath:mapper/*.xml
